### ISSUE TITLE
istio addon telemetry 

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#10]
```

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: addon-api-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTP

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-api-virtual
  namespace: istio-system
spec:
  hosts:
  - "grafana.pilotxxx.co.kr""
  gateways:
  - addon-api-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /
    route:
    - destination:
        host: grafana
        port:
          number: 3000 

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-api-virtual
  namespace: istio-system
spec:
  hosts:
  - "kiali.pilotxxx.co.kr""
  gateways:
  - addon-api-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /
    route:
    - destination:
        host: kiali
        port:
          number: 20001 

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-api-virtual
  namespace: istio-system
spec:
  hosts:
  - "prometheus.pilotxxx.co.kr""
  gateways:
  - addon-api-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /
    route:
    - destination:
        host: prometheus
        port:
          number: 9090 

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tracing-api-virtual
  namespace: istio-system
spec:
  hosts:
  - "tracing.pilotxxx.co.kr"
  gateways:
  - addon-api-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /
    route:
    - destination:
        host: tracing
        port:
          number: 80 



```
