### ISSUE TITLE
istio-1.10.2 manifests istio-ingress 

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#17]
vi /app/istio-1.10.2/manifests/charts/gateways/istio-ingress/values.yaml

```
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:xxxx      
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
