### ISSUE TITLE
Ingress internet-facing istio-ingressgateway

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#18]
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-pub-ingress
  namespace: pilot-service
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-a, subnet-c
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:xxxxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}, {"HTTP": 80}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    #    ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: api-pub-ingress

spec:
  rules:
  - http:
      paths:
        - path: /*
          backend:
            serviceName: ssl-redirect
            servicePort: use-annotation
        - path: /*
          backend:
            serviceName: istio-ingressgateway
            servicePort: 80 
        - path: /*
          backend:
            serviceName: istio-ingressgateway
            servicePort: 443

```
