### ISSUE TITLE
msa Gateway VirtualService

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#19]
```

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api-pvt-gateway
  namespace: pilot-service
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP
    # tls:
    #   httpsRedirect: true
  - hosts:
    - "*"
    port:
      name: https
      number: 443
      protocol: HTTP

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: member-api-pvt-virtual
  namespace: pilot-service
spec:
  hosts:
  - "*"
  gateways:
  - api-pvt-gateway
  http:
  - match:
    - uri:
        exact: /member
    - uri:
        prefix: /member
    route:
    - destination:
        host: api-member-service 
        port:
          number: 8092 
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: system-api-pvt-virtual
  namespace: pilot-service
spec:
  hosts:
  - "*"
  gateways:
  - api-pvt-gateway
  http:
  - match:
    - uri:
        exact: /system
    - uri:
        prefix: /system
    route:
    - destination:
        host: api-system-service 
        port:
          number: 8091 
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: promotion-api-pvt-virtual
  namespace: pilot-service
spec:
  hosts:
  - "*"
  gateways:
  - api-pvt-gateway
  http:
  - match:
    - uri:
        exact: /promotion
    - uri:
        prefix: /promotion
    route:
    - destination:
        host: api-promotion-service 
        port:
          number: 8096
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-api-pvt-virtual
  namespace: pilot-service
spec:
  hosts:
  - "*"
  gateways:
  - api-pvt-gateway
  http:
  - match:
    - uri:
        exact: /product
    - uri:
        prefix: /product
    route:
    - destination:
        host: api-product-service 
        port:
          number: 8093 
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: partnership-api-pvt-virtual
  namespace: pilot-service
spec:
  hosts:
  - "*"
  gateways:
  - api-pvt-gateway
  http:
  - match:
    - uri:
        exact: /partnership
    - uri:
        prefix: /partnership
    route:
    - destination:
        host: api-partnership-service 
        port:
          number: 8101 
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: order-api-pvt-virtual
  namespace: pilot-service
spec:
  hosts:
  - "*"
  gateways:
  - api-pvt-gateway
  http:
  - match:
    - uri:
        exact: /order
    - uri:
        prefix: /order
    route:
    - destination:
        host: api-order-service 
        port:
          number: 8094
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front-api-pvt-virtual
  namespace: pilot-service
spec:
  hosts:
  - "*"
  gateways:
  - api-pvt-gateway
  http:
  - match:
    - uri:
        exact: /front
    - uri:
        prefix: /front
    route:
    - destination:
        host: api-front-service 
        port:
          number: 8097
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cs-api-pvt-virtual
  namespace: pilot-service
spec:
  hosts:
  - "*"
  gateways:
  - api-pvt-gateway
  http:
  - match:
    - uri:
        exact: /cs
    - uri:
        prefix: /cs
    route:
    - destination:
        host: api-cs-service 
        port:
          number: 8095
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: co-api-pvt-virtual
  namespace: pilot-service
spec:
  hosts:
  - "*"
  gateways:
  - api-pvt-gateway
  http:
  - match:
    - uri:
        exact: /co
    - uri:
        prefix: /co
    route:
    - destination:
        host: api-co-service 
        port:
          number: 8090
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - "*"
      exposeHeaders:
      - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cdn-api-pvt-virtual
  namespace: pilot-service
spec:
  hosts:
  - "*"
  gateways:
  - api-pvt-gateway
  http:
  - match:
    - uri:
        exact: /aws
    - uri:
        prefix: /aws
    route:
    - destination:
        host: api-cdn-service
        port:
          number: 8099
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - "*"

```
