### ISSUE TITLE
docker gitlab 설치 

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#23]
```

web:
  image: 'gitlab/gitlab-ce:latest'
  #image: "gitlab/gitlab-ce:12.2.5-ce.0"
  restart: always
  hostname: 'gitlab.example.com'
  container_name: gitlab
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.example.com'
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - './gitlab/config:/etc/gitlab'
    - './gitlab/logs:/var/log/gitlab'
    - './gitlab/data:/var/opt/gitlab'
```

```    

gitlab-rails console -e production

user.password='admin1@#'
user.password_confirmation='admin1@#'
user.save
```

```
--------------------------------------------------------------------------------
 Ruby:         ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
 GitLab:       14.0.5 (25fc1060aff) FOSS
 GitLab Shell: 13.19.0
 PostgreSQL:   12.6
--------------------------------------------------------------------------------

user = User.where(id: 1).first
Loading production environment (Rails 6.1.3.2)
irb(main):001:0> 
irb(main):002:0> 
irb(main):003:0> 
irb(main):004:0> 
irb(main):005:0> user = User.where(id: 1).first
=> #<User id:1 @root>
irb(main):006:0> 

user.password='admin1@#'
user.password_confirmation='admin1@#'
user.save

#

# gitlab-rails console -e production

--------------------------------------------------------------------------------
 Ruby:         ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
 GitLab:       14.0.5 (25fc1060aff) FOSS
 GitLab Shell: 13.19.0
 PostgreSQL:   12.6
--------------------------------------------------------------------------------

user = User.where(id: 1).first
Loading production environment (Rails 6.1.3.2)
irb(main):001:0> 
irb(main):002:0> 
irb(main):003:0> 
irb(main):004:0> 
irb(main):005:0> user = User.where(id: 1).first
=> #<User id:1 @root>
irb(main):006:0> user.password='admin1@#'
=> "admin1@#"
irb(main):007:0> user.password_confirmation='admin1@#'
=> "admin1@#"
irb(main):008:0> user.save
Enqueued ActionMailer::MailDeliveryJob (Job ID: c18d6377-14a3-4ddc-a446-639260cb1564) to Sidekiq(mailers) with arguments: "DeviseMailer", "password_change", "deliver_now", {:args=>[#<GlobalID:0x00007f42bda96030 @uri=#<URI::GID gid://gitlab/User/1>>]}
=> true


```
