### ISSUE TITLE
fluentd Kubernetes log s3

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#26]
```

Kubernetes log는 각 node별 /var/log/containers 밑에 pod별로 로그 생성 
k8s에 daemonSets 를 활용해서 배포

### 설정 및 배포 

docker build
https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.13/debian-s3 로 만든 image
RBAC이고, access key활용으로 바꾸려면, 위에 폴더에서conf/fluent.conf 에 aws key관련 설정 추가 
aws_key_id "#{ENV['S3_ACCESS_KEY']}"
aws_sec_key "#{ENV['S3_SECRET_KEY']}"

docker build/배포(AWS의 경우에는 ECR)
다음 yaml파일을 통해 fluentd daemonSet을 배포하면 됩니다.
DockerRepo/fluentd-kubernetes-daemonset:v1-debian-s3-key-based 가 1번에서 만든 fluentd-s3 image이고 본인이 만들고 배포한 배포URL, Docker Image명으로 사용하면 됩니다.
K8s Secret 에 aws_accesskey 와 aws_secretkey를 설정해줍니다.
S3_BUCKET_NAME, S3_BUCKET_REGION 설정해줍니다.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: kube-system
type: Opaque
stringData:
  aws_accesskey:
  aws_secretkey:
---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      volumes:
        - name: aws-secrets
          secret:
            secretName: aws-secrets
      containers:
      - name: fluentd
        image: DockerRepo/fluentd-kubernetes-daemonset:v1-debian-s3-key-based
        env:
          - name:  S3_BUCKET_NAME
            value: ""
          - name:  S3_BUCKET_REGION
            value: ""
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: aws_accesskey
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: aws_secretkey
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers


```
