### ISSUE TITLE
frontend 환경구성 

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#29]
개발 
```
version: '3'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports: 
      - 3000:3000
    volumes:
      - ./client/src:/client/src
    container_name: react-express-client-dev
    depends_on:
      - server
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./server/src:/server/src
    container_name: react-express-server-dev
```

```
FROM node:12.8.0-alpine
WORKDIR /server
COPY ./package.json .
RUN npm install
COPY ./src ./src
EXPOSE 5000
CMD npm run start:dev
```

운영 
```
version: '3'
services:
  client:
    build: ./client
    ports: 
      - 3000:3000
    container_name: react-express-client-prod
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - 5000:5000
    container_name: react-express-server-prod

```

```
FROM node:12.8.0-alpine
WORKDIR /server
COPY ./package.json .
RUN npm install
COPY ./src ./src
EXPOSE 5000
CMD npm start
```

package.json 
```
{
  "name": "react-express-example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "Nicolas Burgess",
  "scripts": {
    "start": "node src/index.js",
    "start:dev": "nodemon src/index.js",
    "heroku-postbuild": "cd client && npm install --only=dev && npm install && npm run build"
  },
  "keywords": [],
  "license": "ISC",
  "dependencies": {
    "express": "^4.16.3",
    "nodemon": "1.19.1"
  }
}

```
