### ISSUE TITLE
Gateway VirtualService

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#35]
```

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  - pilot-api-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - m.pilot-api.com
    - pc.pilot-api.com
    - bo.pilot-api.com
    - co.pilot-api.com
    - api.pilot-api.com
    - api2.pilot-api.com  
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: prod-pilot-com-cert
      mode: SIMPLE
   - hosts:
    - m.pilot-api.com
    - pc.pilot-api.com
    - bo.pilot-api.com
    - co.pilot-api.com
    - api.pilot-api.com
    - api2.pilot-api.com      
    port:
      name: http
      number: 80
      protocol: HTTP  
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front-mobile
spec:
  hosts:
  - m.pilot-api.com
  gateways:
  - pilot-api-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: front-mobile
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-member-virtual
  namespace: pilot-service
spec:
  hosts:
  - api.pilot-api.com
  gateways:
  - pilot-api-gateway
  http:
  - match:
    - uri:
        exact: /member
    - uri:
        prefix: /member
    route:
    - destination:
        host: api-member-service
        port:
          number: 8092
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-system-virtual
  namespace: pilot-service
spec:
  hosts:
  - api.pilot-api.com
  gateways:
  - pilot-api-gateway
  http:
  - match:
    - uri:
        exact: /system
    - uri:
        prefix: /system
    route:
    - destination:
        host: api-system-service 
        port:
          number: 8091

```
