### ISSUE TITLE
Argocd Lens

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#39]
```

# 1. Install Argo CD
#### k8s 명령어  
```bash 
kubectl config get-contexts

kubectl config use-context docker-desktop
```

* Lens 툴을 사용해 helm 으로 argocd 설치  

#### 1. argocd 네임스페이스 생성 
```bash 
kubectl create namespace argocd
```

#### 3. Ingress 생성 
* Jenkins 서버

```bash 
cd /home/ec2-user/apps/apps/argo/v2-install

kubectl apply -f argo-ingress.yaml
```
* argo-ingress.yaml
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-ingress-internal
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-path: /login
    alb.ingress.kubernetes.io/subnets: subnet-06762d04b812c92c3,subnet-0fa0948e844928acf
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:392812150308:certificate/9cdd6996-2224-4933-8743-c4ba38c09f05
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}, {"HTTP": 80}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    #ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: argocd-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
    - host: argocd.stg.chicor.co.kr
      http:
        paths:
          - backend:
              serviceName: argo-cd-1626842105-argocd-server
              servicePort: 443
```

#### 4. argocd LoadBalancer or NodePort

kuectl patch svc argo-cd-1626842105-argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

internal-k8s-argocd-argocdin-c813ada381-1655486323.ap-northeast-2.elb.amazonaws.com

#### 5. Route 53 

argocd.stg.chicor.co.kr 

#### 6. 비밀번호 확인 

https://argocd.stg.chicor.co.kr/applications

username: admin

kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

vYcSFYVfdQfkAsle

#### mac 에서 

kubectl create namespace argocd

helm repo add argo https://argoproj.github.io/argo-helm

helm install argocd argo/argo-cd \
-f https://gist.githubusercontent.com/pcrete/250896d4ff90ce2afa496c9f515b6be5/raw/0057742a532e8dfd578c139385537cd39de07f03/argocd-values.yaml \
--version 2.6.0 \
--namespace argocd

kubectl port-forward service/argocd-server -n argocd 8181:443

http://localhost:8181 

username: admin

kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

# mac 
UejFOIjHDryOqHjK

kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

#### helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

##### kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

##### Argocd

https://argoproj.github.io/argo-cd/getting_started/#2-download-argo-cd-cli

https://aws.amazon.com/ko/blogs/opensource/connecting-aws-managed-services-to-your-argo-cd-pipeline-with-open-source-crossplane/
```
