### ISSUE TITLE
gitlab runner 

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#40]
```
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "ryu"
  url = "http://gitlab.example.com/"
  token = "Azu5_RgXqLmCwoFbNEog"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ruby:2.6"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
```
```
NGINX_VERSION=1.20.1-alpine
#GITLAB_VERSION=13.8.1-ce.0
GITLAB_VERSION=latest
GITLAB_ROOT_PASSWORD=admin!23
GITLAB_RUNNER_VERSION=alpine-v13.8.0
DOCKER_REGISTRY_VERSION=2.7.1
REDIS_VERSION=6.0.10
POSTGRES_VERSION=12-alpine
POSTGRES_GITLAB_PASSWORD=admin!23
BASE_DOMAIN=gitlab.example.com
```

```
version: '3.9'
services:
  ######################################## Gitlab ########################################
  gitlab:
    container_name: 'gitlab-web'
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile-gitlab
      args:
        - GITLAB_VERSION=${GITLAB_VERSION}
        - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}
        - POSTGRES_GITLAB_PASSWORD=${POSTGRES_GITLAB_PASSWORD}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        from_file('/omnibus_config.rb')
        external_url "http://gitlab.example.com"
    networks: 
      - default
      - gitlab-backend
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    depends_on:
      - redis
      - postgres
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
    cpus: 2
    mem_limit: 3G
  
  ######################################## Docker Registry ########################################
  registry:
    container_name: 'gitlab-registry'
    restart: unless-stopped
    build: 
      context: .
      dockerfile: docker/Dockerfile-registry
      args:
        - DOCKER_REGISTRY_VERSION=${DOCKER_REGISTRY_VERSION}
    environment: 
      - REGISTRY_HTTP_HOST=https://registry.hackinglab.local:5000
    networks: 
      - gitlab-backend
    volumes: 
      - registry-data:/var/lib/registry
    cpus: 1
    mem_limit: 150M

  ######################################## Redis ########################################
  redis:
    container_name: 'gitlab-redis'
    restart: unless-stopped
    image: redis:6.0.10
    volumes:
      - redis-data:/var/lib/redis:Z
    networks: 
      - gitlab-backend
    cpus: 1
    mem_limit: 150M

  ######################################## Postgres ########################################
  postgres:
    container_name: 'gitlab-postgres'
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=gitlabhq_production
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=${POSTGRES_GITLAB_PASSWORD}
    networks: 
      - gitlab-backend
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    cpus: 2
    mem_limit: 300M

volumes:
  gitlab-data:
  gitlab-config:
  gitlab-logs:
  redis-data:
  postgresql-data:
  registry-data:

networks:
  gitlab-backend:
```

```
version: '3'
services:

  gitlab-runner:
    container_name: gitlab-runner
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    volumes:
      - './gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

```

docker exec -it gitlab-runner gitlab-runner register \
  --non-interactive \
  --url "http://gitlab.example.com" \
  --registration-token "Azu5_RgXqLmCwoFbNEog" \
  --executor "docker" \
  --docker-image alpine:latest \
  --description "docker-runner" \
  --tag-list "docker,aws" \
  --run-untagged="true" \
  --locked="false" \
  --access-level="not_protected"


```
