### ISSUE TITLE
jenkins nexus sonarqube 

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#51]
```

version: "3"
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    environment:
      - DOCKER_HOST=tcp://localhost:2375
      - JENKINS_UC=http://updates.jenkins.io
      - JENKINS_UC_EXPERIMENTAL=http://updates.jenkins.io/experimental
      - JENKINS_INCREMENTALS_REPO_MIRROR=http://repo.jenkins-ci.org/incrementals
    user: root
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./data/jenkins-data:/var/jenkins_home
      - ./data/jenkins-home:/home

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - "./data/nexus-data:/nexus-data"
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - devnet

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: always
    ports:
    - "9000:9000"
    networks:
      - devnet
    depends_on:
      - sonardb
    links:
      - sonardb
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - "./data/sonar/:/var/lib/sonar"

  sonardb:
    networks:
      - devnet
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    - POSTGRESQL_DB=sonar
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql"

networks:
  devnet:
    driver: bridge

```
