### ISSUE TITLE
hashicorp/terraform docker-compose 

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#59]
```
version: '3.7'

services:
    tf:
        image: hashicorp/terraform:0.13.3
        volumes:
        - .:/infra
        working_dir: /infra

    ubuntu:
        image: ubuntu:latest
        volumes:
        - .:/key
        working_dir: /key
    
    python:
        image: python:3
        volumes:
        - .:/workspace
        working_dir: /workspace

```
