### ISSUE TITLE
django-sample-for-docker-compose

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#67]
```

version: '3'

volumes:
  django_sample_db_dev: {}

services:
  db:
    image: postgres
    volumes:
      - django_sample_db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplesecret
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplesecret
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0:8000
    restart: always
    volumes:
      - ./:/app/

```

```
FROM python:3

RUN apt-get update && apt-get -y install \
    libpq-dev

WORKDIR /app
ADD    ./requirements.txt   /app/
RUN    pip install -r requirements.txt

ADD    ./djangosample   /app/djangosample/
ADD    ./manage.py      /app/

CMD ["python", "manage.py", "runserver", "0:8000"]

```

```
FROM python:3

ENV PYTHONUNBUFFERED 0

RUN apt-get update && apt-get -y install \
    libpq-dev

WORKDIR /app

ADD    requirements.txt    /app/
RUN    pip install -r requirements.txt

```
