### ISSUE TITLE
jenkins_jmeter_Dockerfile

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#7]
```

version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'jenkins_docker'
    restart: always
    ports:
      - '8200:8080'
      - '50200:50000'
    expose:
      - '8080'
      - '50000'
    volumes:
      - './jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      TZ: "Asia/Seoul"

```

```
#FROM jenkins/jenkins:lts
FROM jenkins/jenkins:latest

USER root 

#COPY docker_install.sh /docker_install.sh
#RUN chmod +x /docker_install.sh

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# installing chrome driver
RUN apt-get update && apt-get -qq -y install curl

# Update the package list and install chrome
RUN apt-get update -y

ARG JMETER_VERSION="5.4.1"
ENV JMETER_HOME /opt/apache-jmeter-${JMETER_VERSION}
ENV JMETER_BIN  /opt/apache-jmeter-${JMETER_VERSION}/bin
ENV JMETER_DOWNLOAD_URL  https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz

ENV JAVA_HOME=/opt/java/openjdk

WORKDIR /opt/apache-jmeter-${JMETER_VERSION}

ARG TZ=Asia/Seoul

RUN wget http://apache.stu.edu.tw//jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz
RUN tar -xzf apache-jmeter-${JMETER_VERSION}.tgz 
RUN mv apache-jmeter-${JMETER_VERSION}/* /opt/apache-jmeter-${JMETER_VERSION}
RUN rm -r /opt/apache-jmeter-${JMETER_VERSION}/apache-jmeter-${JMETER_VERSION}

RUN chmod +x /opt/apache-jmeter-${JMETER_VERSION}/bin/jmeter

#
RUN mkdir code/

USER jenkins
RUN /usr/local/bin/install-plugins.sh \
blueocean 

#RUN /docker_install.sh
```
