### ISSUE TITLE
elk-prometheus-grafana-movies

### ISSUE THREAD

**Issue by jiman94** [jiman94/gitlab_terraform#92]
```yaml 
version: "3.8"

services:

  mysql:
    image: mysql:8.0.26
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=moviesdb
      - MYSQL_ROOT_PASSWORD=secret
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    command: 
      - bash 
      - -c 
      - |
        cat>/docker-entrypoint-initdb.d/z99_dump.sql <<EOF
        
        use mysql;
        ALTER USER 'root'@'%' IDENTIFIED WITH 'mysql_native_password' BY 'secret';
        GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'; 
        GRANT GRANT OPTION ON *.* TO 'root'@'%'; 

        CREATE USER 'app_user'@'%' IDENTIFIED WITH 'mysql_native_password' BY 'secret';
        GRANT ALL PRIVILEGES ON *.* TO 'app_user'@'%'; 
        GRANT GRANT OPTION ON *.* TO 'app_user'@'%'; 

        CREATE database demo;

        use demo;

        create table CUSTOMERS (
                id INT PRIMARY KEY,
                first_name VARCHAR(50),
                last_name VARCHAR(50),
                email VARCHAR(50),
                gender VARCHAR(50),
                club_status VARCHAR(8),
                comments VARCHAR(90),
                create_ts timestamp DEFAULT CURRENT_TIMESTAMP ,
                update_ts timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        );

        EOF
        # Launch mysql
        docker-entrypoint.sh mysqld
        #
        sleep infinity




  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      cluster.name: docker-es-cluster
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: "curl -f http://localhost:9200 || exit 1"
      start_period: 30s

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    container_name: logstash
    restart: unless-stopped
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch
    healthcheck:
      test: "curl -f http://localhost:9600 || exit 1"
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    healthcheck:
      test: "curl -f http://localhost:5601 || exit 1"
      start_period: 30s

  filebeat:
    build: filebeat
    container_name: filebeat
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
    depends_on:
      - elasticsearch
      - logstash

  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9090" ]
      start_period: 30s

  grafana:
    image: grafana/grafana:8.1.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3000" ]
      start_period: 30s

```
